# Generated by Django 5.0.2 on 2026-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Customer id after keep-profile checkout (cus_…).', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Subscription id for Forma billing (sub_…).', max_length=255),
        ),
    ]
