# Generated by Django 6.0.4 on 2026-04-09 21:02

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(help_text='One line — what you do and for whom.', max_length=80)),
                ('bio', models.TextField(help_text='Longer profile copy.')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='trainer/portraits/')),
                ('quick_qualifications', models.JSONField(blank=True, default=pages.models._empty_list)),
                ('training_locations', models.JSONField(blank=True, default=pages.models._empty_list)),
                ('primary_area', models.CharField(blank=True, max_length=128)),
                ('postcode_district', models.CharField(blank=True, max_length=16)),
                ('other_areas', models.JSONField(blank=True, default=pages.models._empty_list)),
                ('free_consultation', models.BooleanField(default=False)),
                ('instagram_handle', models.CharField(blank=True, help_text='Without @; stored plain.', max_length=64)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages_trainer_profile',
            },
        ),
        migrations.CreateModel(
            name='TrainerPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('unit_note', models.CharField(blank=True, help_text='e.g. per session', max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='pages.trainerprofile')),
            ],
            options={
                'db_table': 'pages_trainer_price_tier',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'order'), name='pages_price_unique_order')],
            },
        ),
        migrations.CreateModel(
            name='TrainerGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainer/gallery/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='pages.trainerprofile')),
            ],
            options={
                'db_table': 'pages_trainer_gallery_photo',
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'slot'), name='pages_gallery_unique_slot')],
            },
        ),
        migrations.CreateModel(
            name='TrainerAdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_qualifications', to='pages.trainerprofile')),
            ],
            options={
                'db_table': 'pages_trainer_add_qual',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'order'), name='pages_add_qual_unique_order')],
            },
        ),
        migrations.CreateModel(
            name='TrainerSpecialism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisms', to='pages.trainerprofile')),
            ],
            options={
                'db_table': 'pages_trainer_specialism',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'order'), name='pages_spec_unique_order')],
            },
        ),
    ]
