# Generated by Django 5.0.2 on 2026-04-11 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_primaryarea_postcodedistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Optional short intro clip (e.g. MP4 or WebM).', max_length=255, null=True, upload_to='trainer/intro/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'm4v'))]),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='show_intro_video',
            field=models.BooleanField(default=True, help_text='When on, the intro video block is shown on your public profile. If there is no clip yet, visitors see a placeholder.'),
        ),
    ]
