# Generated by Django 5.0.2 on 2026-04-11 17:39

import pages.models
from django.db import migrations, models


def bump_completed_onboarding_step(apps, schema_editor):
    TrainerProfile = apps.get_model('pages', 'TrainerProfile')
    TrainerProfile.objects.filter(completed_at__isnull=False, onboarding_step=6).update(onboarding_step=7)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_trainerprofile_intro_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='client_reviews',
            field=models.JSONField(blank=True, default=pages.models._empty_list, help_text='Up to three {name, quote} objects from onboarding.'),
        ),
        migrations.RunPython(bump_completed_onboarding_step, noop),
    ]
