# Generated by Django 5.0.2 on 2026-04-12 07:29

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_trainerprofile_quick_qualification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Shown to clients who want to reach you by email.', max_length=254),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Digits, spaces, and leading + are fine.', max_length=32),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='contact_phone_preference',
            field=models.CharField(blank=True, choices=[('call', 'Phone call'), ('whatsapp', 'WhatsApp'), ('text', 'Text message')], help_text='How you prefer clients to use this number.', max_length=16, verbose_name='Call, WhatsApp, or text'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='client_reviews',
            field=models.JSONField(blank=True, default=pages.models._empty_list, help_text='Up to three {name, quote, rating 1–5, confirmed, focus?} objects from onboarding.'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='quick_qualification_notes',
            field=models.JSONField(blank=True, default=pages.models._empty_dict, help_text='Maps quick preset keys to short text shown on the public profile.'),
        ),
    ]
