# Generated by Django 5.0.2 on 2026-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_trainer_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerspecialism',
            name='description',
            field=models.CharField(blank=True, help_text='Optional: one short sentence explaining this specialism for clients.', max_length=280),
        ),
    ]
