# Generated by Django 5.0.2 on 2026-04-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_trainer_specialism_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='contact_phone_preference',
            field=models.CharField(blank=True, choices=[('call', 'Phone call'), ('whatsapp', 'WhatsApp'), ('text', 'Text message')], help_text='How you prefer clients to use this number (shown on your public page).', max_length=16, verbose_name='Preferred contact method'),
        ),
    ]
