# Generated by Django 5.0.14 on 2026-04-19 17:53

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_trainerpricetier_is_most_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='client_reviews',
            field=models.JSONField(blank=True, default=pages.models._empty_list, help_text='Up to three {name, quote, rating 1–5, confirmed, focus?, slot 0–2} objects from onboarding.'),
        ),
    ]
