# Generated by Django 5.0.2 on 2026-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_canonical_specialism_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, default='', help_text='Optional context — goals, area, timing, etc.', max_length=5000, verbose_name='Additional information')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'profile enquiry',
                'verbose_name_plural': 'profile enquiries',
                'db_table': 'pages_profile_enquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialismcatalog',
            options={'ordering': ['title']},
        ),
    ]
