# Generated by Django 5.0.2 on 2026-04-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_nine_canonical_specialisms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, help_text='Venue or chain name, e.g. a specific gym’s name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='e.g. neighbourhood, area, or part of the city (not a full address required)', max_length=300)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='pages.trainerprofile')),
            ],
            options={
                'db_table': 'pages_trainer_gym',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainergym',
            constraint=models.UniqueConstraint(fields=('profile', 'order'), name='pages_gym_unique_order'),
        ),
    ]
