# Generated by Django 5.0.2 on 2026-04-24 21:37

import django.db.models.deletion
from django.db import migrations, models


def copy_location_to_area(apps, schema_editor):
    TrainerGym = apps.get_model('pages', 'TrainerGym')
    PrimaryArea = apps.get_model('pages', 'PrimaryArea')
    for g in TrainerGym.objects.exclude(location__exact='').iterator():
        raw = (g.location or '').strip()
        if not raw:
            continue
        pa = PrimaryArea.objects.filter(name__iexact=raw).first()
        if pa:
            g.location_area_id = pa.pk
            g.save(update_fields=['location_area_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_trainer_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainergym',
            name='location_area',
            field=models.ForeignKey(
                blank=True,
                help_text='Coverage area for this venue (from the shared catalogue, or add one in onboarding).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainer_gyms',
                to='pages.primaryarea',
            ),
        ),
        migrations.RunPython(copy_location_to_area, noop_reverse),
        migrations.RemoveField(
            model_name='trainergym',
            name='location',
        ),
    ]
