# Generated by Django 5.0.2 on 2026-04-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_trainer_gym_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='years_experience',
            field=models.SmallIntegerField(blank=True, help_text='Years you have been training clients (optional; shown in the public profile stats).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
