# Generated by Django 5.0.2 on 2026-04-25 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_trainerprofile_years_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specialismcatalog',
            index=models.Index(fields=['is_active', 'title'], name='pages_spec_cat_active_title'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(condition=models.Q(('forma_made', True), ('created_by__isnull', False)), fields=['created_by', 'id'], name='pages_trf_createdby_id_f'),
        ),
    ]
