# Generated by Django 5.0.2 on 2026-04-26 15:19

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_add_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='client_reviews',
            field=models.JSONField(blank=True, default=pages.models._empty_list, help_text='List of {name, quote, rating 1–5, confirmed, focus?, slot} from onboarding; slot is a non-negative list index.'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='featured_review_slot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Index of the review in client_reviews to show as the large standout quote; null = none.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
