# Generated by Django 5.0.2 on 2026-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_django_cache_table_for_shared_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=512)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'pages_profile_pageview',
                'indexes': [models.Index(fields=['page', 'ts'], name='pages_profi_page_67d508_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileScrollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=512)),
                ('depth', models.PositiveSmallIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'pages_profile_scroll_event',
                'indexes': [models.Index(fields=['page', 'ts'], name='pages_profi_page_3cbd75_idx')],
            },
        ),
    ]
