# Generated by Django 5.0.2 on 2026-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_profile_analytics_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='forma_outreach_call_1',
            field=models.BooleanField(default=False, help_text='Staff checklist on Forma-made list: first call touchpoint done.'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='forma_outreach_email_1',
            field=models.BooleanField(default=False, help_text='Staff checklist on Forma-made list: first email touchpoint done.'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='forma_outreach_email_2',
            field=models.BooleanField(default=False, help_text='Staff checklist on Forma-made list: second email touchpoint done.'),
        ),
    ]
