# Generated by Django 5.0.14 on 2026-05-01 06:11

import django.core.validators
import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_forma_staff_outreach_checkboxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=80)),
                ('client_last_initial', models.CharField(max_length=1)),
                ('client_job_title', models.CharField(blank=True, max_length=120)),
                ('client_location', models.CharField(blank=True, max_length=120)),
                ('client_specialism', models.CharField(blank=True, max_length=120)),
                ('star_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('outcome_tags', models.JSONField(blank=True, default=pages.models._empty_list, help_text='One or two tags from PROOF_OUTCOME_TAG_CHOICES.')),
                ('prompt_start', models.TextField(help_text='Where were you when you started working with this practitioner?', max_length=1200)),
                ('prompt_change', models.TextField(help_text='What changed?', max_length=1200)),
                ('prompt_recommend', models.TextField(help_text='What would you tell someone thinking about training with them?', max_length=1200)),
                ('video', models.FileField(max_length=255, upload_to='proof/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'm4v'))])),
                ('share_to_instagram', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_testimonials', to='pages.trainerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_testimonials_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages_proof_testimonial',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['profile', 'status', '-submitted_at'], name='pages_proof_profile_status_idx')],
            },
        ),
    ]
