# Generated by Django 5.0.14 on 2026-05-01 06:20

from django.db import migrations, models


def _seed_outcome_tags(apps, schema_editor):
    ProofOutcomeTag = apps.get_model('pages', 'ProofOutcomeTag')
    defaults = [
        ('lost_weight', 'Lost weight'),
        ('built_strength', 'Built strength'),
        ('recovered_from_injury', 'Recovered from injury'),
        ('improved_mental_health', 'Improved mental health'),
        ('ran_first_race', 'Ran first race'),
        ('back_pain_gone', 'Back pain gone'),
        ('got_off_medication', 'Got off medication'),
    ]
    for idx, (key, label) in enumerate(defaults, start=1):
        ProofOutcomeTag.objects.update_or_create(
            key=key,
            defaults={
                'label': label,
                'sort_order': idx,
                'is_active': True,
            },
        )


def _unseed_outcome_tags(apps, schema_editor):
    ProofOutcomeTag = apps.get_model('pages', 'ProofOutcomeTag')
    ProofOutcomeTag.objects.filter(
        key__in=[
            'lost_weight',
            'built_strength',
            'recovered_from_injury',
            'improved_mental_health',
            'ran_first_race',
            'back_pain_gone',
            'got_off_medication',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_prooftestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOutcomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pages_proof_outcome_tag',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(_seed_outcome_tags, _unseed_outcome_tags),
    ]
