# Generated by Django 5.0.2 on 2026-05-01 15:12

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_prooftestimonial_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prooftestimonial',
            name='suggested_quotes',
            field=models.JSONField(blank=True, default=pages.models._empty_list, help_text='AI-suggested short pull-quote candidates.'),
        ),
    ]
