# Generated by Django 5.0.2 on 2026-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_prooftestimonial_suggested_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prooftestimonial',
            name='poster',
            field=models.ImageField(blank=True, upload_to='proof/posters/'),
        ),
    ]
