# Generated by Django 5.0.2 on 2026-05-07 19:18

from django.db import migrations


NEW_DEFAULTS = [
    ('lost_weight', 'Lost weight'),
    ('built_strength', 'Built strength'),
    ('recovered_from_injury', 'Recovered from injury'),
    ('improved_mental_health', 'Improved mental health'),
    ('ran_first_race', 'Ran first race'),
    ('back_pain_gone', 'Back pain gone'),
    ('got_off_medication', 'Got off medication'),
    ('more_energy', 'More energy'),
    ('first_time_in_the_gym', 'First time in the gym'),
    ('trained_through_pregnancy', 'Trained through pregnancy'),
]


def _forward(apps, schema_editor):
    ProofOutcomeTag = apps.get_model('pages', 'ProofOutcomeTag')
    active_keys = []
    for idx, (key, label) in enumerate(NEW_DEFAULTS, start=1):
        active_keys.append(key)
        ProofOutcomeTag.objects.update_or_create(
            key=key,
            defaults={
                'label': label,
                'sort_order': idx,
                'is_active': True,
            },
        )
    ProofOutcomeTag.objects.exclude(key__in=active_keys).update(is_active=False)


def _reverse(apps, schema_editor):
    # Keep reverse non-destructive.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_prooftestimonial_poster'),
    ]

    operations = [
        migrations.RunPython(_forward, _reverse),
    ]
