"""
Django settings for forma_project project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env next to manage.py so os.getenv sees DJANGO_SECRET_KEY (etc.)
load_dotenv(BASE_DIR / '.env')


def _split_csv(value: str) -> list[str]:
    return [part.strip() for part in value.split(',') if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# Production: set DJANGO_DEBUG=0 (or false). Default is development-friendly.
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

# Comma-separated hostnames, e.g. ALLOWED_HOSTS=example.com,127.0.0.1,localhost
_allowed = os.getenv('ALLOWED_HOSTS', '').strip() or os.getenv('DJANGO_ALLOWED_HOSTS', '').strip()
_local_hosts = ('127.0.0.1', 'localhost')
if not DEBUG:
    if not _allowed:
        raise ImproperlyConfigured(
            'Set ALLOWED_HOSTS (or DJANGO_ALLOWED_HOSTS) to a comma-separated list of '
            'hostnames when DJANGO_DEBUG is off.'
        )
    ALLOWED_HOSTS = _split_csv(_allowed)
else:
    if _allowed:
        # Same .env as production: keep listed hosts and always allow local runserver.
        ALLOWED_HOSTS = list(dict.fromkeys(_split_csv(_allowed) + list(_local_hosts)))
    else:
        ALLOWED_HOSTS = list(_local_hosts)

# Comma-separated full origins, e.g. https://app.example.com
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip() or os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS', ''
).strip()
_local_csrf_origins = ('http://127.0.0.1:8000', 'http://localhost:8000')
if DEBUG:
    merged_csrf = list(dict.fromkeys(_split_csv(_csrf_origins) + list(_local_csrf_origins)))
    if merged_csrf:
        CSRF_TRUSTED_ORIGINS = merged_csrf
elif _csrf_origins:
    CSRF_TRUSTED_ORIGINS = _split_csv(_csrf_origins)

if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when DJANGO_DEBUG is off.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'pages',
]

_use_s3_media = bool(os.getenv('AWS_STORAGE_BUCKET_NAME', '').strip())
if _use_s3_media:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forma_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forma_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_db_host = os.getenv('DB_HOST', '').strip()
if _db_host:
    _db = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres').strip(),
        'USER': os.getenv('DB_USER', 'postgres').strip(),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': _db_host,
        'PORT': os.getenv('DB_PORT', '5432').strip(),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
    _sslmode = os.getenv('DB_SSLMODE', 'require').strip()
    if _sslmode and _sslmode.lower() not in ('disable', 'false', '0'):
        _db['OPTIONS'] = {'sslmode': _sslmode}
    DATABASES = {'default': _db}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

if _use_s3_media:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '').strip()
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '').strip()
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '').strip()
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-north-1').strip()
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    }
    _bucket = AWS_STORAGE_BUCKET_NAME
    _region = AWS_S3_REGION_NAME
    MEDIA_URL = f'https://{_bucket}.s3.{_region}.amazonaws.com/'
    MEDIA_ROOT = None
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    }
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/logged-out/'

# Stripe (keep-profile checkout — use test keys in .env for development)
STRIPE_SECRET_KEY = os.getenv('STRIPE_SK', '').strip()
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PK', '').strip()
STRIPE_PRODUCT_ID = os.getenv('STRIPE_PRODUCT_ID', '').strip()
STRIPE_PRICE_ID = os.getenv('STRIPE_PRICE_ID', '').strip()
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '').strip()
STRIPE_TRIAL_DAYS = int(os.getenv('STRIPE_TRIAL_DAYS', '30') or 30)

# Railway / Heroku / other HTTPS reverse proxies: set DJANGO_SECURE_PROXY_SSL=1
if os.getenv('DJANGO_SECURE_PROXY_SSL', '').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
